/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author erina ung
 */
public class LoginPage extends javax.swing.JFrame {

    private final LoginCredentialsQuery login;
    private final StaffQuery staffQuery;
    private String type;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        login = new LoginCredentialsQuery();
        staffQuery = new StaffQuery();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        genetechLogo = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        backdrop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Login");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genetechLogo.setFont(new java.awt.Font("Georgia", 0, 60)); // NOI18N
        genetechLogo.setForeground(new java.awt.Color(238, 238, 238));
        genetechLogo.setText("Genetech");
        jInternalFrame1.getContentPane().add(genetechLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2assignment/logo glow.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jInternalFrame1.getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 188, 210, 30));

        usernameLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(238, 238, 238));
        usernameLabel.setText("Username:");
        jInternalFrame1.getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        passwordLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(238, 238, 238));
        passwordLabel.setText("Password:");
        jInternalFrame1.getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, 30));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 230, 90, 40));

        backdrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2assignment/backdrop.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(backdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(-13, 0, 570, 333));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    // get username field and password field and match it to an account from 
    // database 
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        int id = Integer.parseInt(usernameField.getText());
        String pass = new String(this.passwordField.getPassword());
        type = login.getUserType(id, pass);
        if (type != null) {
            HomePage home = new HomePage();
            home.setVisible(true);
            home.setAccessLevel(type);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Incorrect ID/Password combination");
            passwordField.setText("");
        }

// TODO add your handling code here

    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backdrop;
    private javax.swing.JLabel genetechLogo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logoImage;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
